namespace TheMobileShopCodeFirstFromDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    
    /// <summary>
    /// Corresponds to the Employee table in the database
    /// </summary>
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            Transactions = new HashSet<Transaction>();
        }
        //Autogenerated unique ID for every employee
        public int EmployeeId { get; set; }
        
        //Unique employee code to login to the application to process any transaction
        [Required]
        [StringLength(7)]
        public string EmployeeCode { get; set; }
        
        /// <summary>
        /// General employee details in the employee table
        /// </summary>
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [StringLength(15)]
        public string PhoneNumber { get; set; }

        [StringLength(50)]
        public string Email { get; set; }
        
        //employee is an admin or a regular employee as the data access will be differed accordingly
        public byte IsAdmin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        // list of employees made transactions in the transactions table
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
